name: Build & Sanity
on: [push, pull_request]

jobs:
  run-sanity-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy minikube
        uses: medyagh/setup-minikube@latest
        id: minikube
        with:
          cache: false
          minikube-version: 1.29.0
          driver: docker
          container-runtime: containerd
          kubernetes-version: v1.26.1
          cpus: 4
          memory: 4000m

      - name: Run make tester
        run: make tester

      - name: Run Build & Sanity Tests
        run: |
          cd ./src/test/framework/
          sudo ./run_test_job.sh --name sanity --image noobaa --tester_image noobaa-tester --job_yaml ../../../.travis/travis_test_job.yaml --tests_list ./sanity_tests_list.js --wait
