name: Build & Sanity

# Run on each new PR and each new push to existing PR
on: [push, pull_request]

jobs:
  run-sanity-tests:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: container-tools/kind-action@v1

      # - name: Deploy minikube
      #   id: deploy
      #   run: sudo bash ./.travis/deploy_minikube.sh

      - name: Check Kind cluster
        run: |
          pwd
          kind get kubeconfig > $(pwd)/kubeconfig
          export KUBECONFIG="$(pwd)/kubeconfig"
          kind version
          kubectl cluster-info
          kubectl get pods -n kube-system
          echo "current-context:" $(kubectl config current-context)
          echo "environment-kubeconfig:" ${KUBECONFIG}
          sudo chown $(id -u):$(id -g) $(pwd)/kubeconfig
        # mkdir -p $HOME/.kube
        # sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config

        # sudo kubeadm init --pod-network-cidr=10.244.0.0/16
      # - name: Run make tester
      #   id: run-make-tester
      #   run: make tester || exit 1

      - name: Run Build & Sanity Tests
        id: run-sanity
        run: |
          docker pull liranmauda/noobaa-tester:1
          docker tag liranmauda/noobaa-tester:1 noobaa-tester
          cd ./src/test/framework/
          sudo ./run_test_job.sh --name sanity --image noobaa --tester_image noobaa-tester --job_yaml ../../../.travis/travis_test_job.yaml --tests_list ./pipeline_tests_list.js --wait || exit 1
